Add S3 Uploader
MaxMaeder/DriveBackupV2 pull request #123
Opened 2023-04-08 18:05 UTC by vpzomtrrfrt

Should resolve #61 (though it seems to have already been closed?)

2023-04-09 03:23 UTC, MaxMaeder approved these changes
LGTM!! Thanks for contributing!

2023-04-09 07:38 UTC, rhld16 commented
Two minor changes requested, but other than that - looks great! Thanks for contributing 😃

2023-04-10 03:54 UTC, vpzomtrrfrt commented
What would those changes be?

2023-05-28 11:55 UTC, rhld16 commented
@vpzomtrrfrt Sorry for the delay, take a look at my review to see the requested changes

2023-07-13 00:13 UTC, vpzomtrrfrt commented
I don't see a review from you

2024-01-24 17:33 UTC, lrmtheboss submitted a review, later dismissed
Just a couple of small changes

2024-01-24 17:33 UTC, lrmtheboss commented on DriveBackup/src/main/java/ratismal/drivebackup/TestThread.java
> +                    sendMethodDisabled(logger, NextcloudUploader.UPLOADER_NAME);
Should be using S3Uploader instead of NextcloudUploader

2024-01-24 17:37 UTC, lrmtheboss requested changes
Just a couple of small changes

2024-01-24 22:42 UTC, rhld16 requested changes

2024-01-24 22:42 UTC, rhld16 commented on DriveBackup/src/main/java/ratismal/drivebackup/uploaders/s3/S3Uploader.java
> +    public MinioClient minioClient;
This client should be private

2024-04-09 17:41 UTC, lrmtheboss approved these changes
LGTM just need to test now

2024-04-10 00:14 UTC, lrmtheboss commented
Just tested with a local minio server, and worked fine

2024-04-10 00:14 UTC, merged